version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_TODAYProject
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_today.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_GIT_TODAYProject
    version: "1.0"
- serviceName: project.siqa_git_today.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_GIT_TODAYProject
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: project.siqa_git_today.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_GIT_TODAYProject
    version: "1.0"
- serviceName: project.siqa_git_today.integrations:deepclonetest
  packages:
  - name: SIQA_GIT_TODAYProject
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2061
